# -*- coding: utf-8 -*-
"""HolaMundo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kYSV6ttelEJ_rsmg6oGRVjOdUq2BMhAW
"""

#Primer Hola Mundo con GitHub 

print("Hola Mundo")